
# ==================== 订阅节点 ====================
# 在 url 中填写自己的订阅链接；每个订阅名称必须唯一。
proxy-providers:
  dcsip: #更改名称为你想要的名称
    url: "" # 你的订阅地址
    type: http
    interval: 3600 # 更新间隔 单位秒
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204", interval: 100} # 健康检查 单位秒
    # override: # 区分不同订阅的节点前缀,如果不需要可以删除或者注释掉
    #   additional-prefix: "[]" # 节点前缀
  # 多个订阅可以继续添加,取消注释即可
  # provider2:
  #   url: ""  # 你的订阅地址
  #   type: http
  #   interval: 1800
  #   health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 100}
  #   override:
  #     additional-prefix: "[]"

  # provider3:
  #   url: ""  # 你的订阅地址
  #   type: http
  #   interval: 1800
  #   health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 100}
  #   override:
  #    additional-prefix: "[]"

# # 手动添加固定节点；默认直连，可按需取消注释。
# proxies: 
#   - name: "直连"
#     type: direct
#     udp: true

# ==================== 控制面板 ====================
# 控制 API 地址；127.0.0.1 表示只允许本机访问。
external-controller: 127.0.0.1:9090
# UI 下载并解压到 Mihomo 运行目录下的 ui 文件夹。
external-ui: ui
# UI 不存在时，从此地址下载。
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
# 允许访问控制 API 的网页来源。
external-controller-cors:
  allow-origins:
    - https://metacubex.github.io
    - https://board.zash.run.place
    - https://github.com
  allow-private-network: false
# 控制 API 密钥；请勿公开。
secret:
# ==================== 基本运行设置 ====================
ipv6: false
mode: rule
# HTTP 和 SOCKS5 共用端口。
mixed-port: 7890
socks-port: 0
port: 0
redir-port: 0
tproxy-port: 0
# 是否允许局域网设备连接本机代理。
allow-lan: false
unified-delay: false
tcp-concurrent: false
log-level: info
find-process-mode: always
interface-name: ""
bind-address: "*"
keep-alive-idle: 0
keep-alive-interval: 0
disable-keep-alive: false
lan-allowed-ips:
  - 0.0.0.0/0
  - ::/0
lan-disallowed-ips: []
authentication: []
skip-auth-prefixes:
  - 127.0.0.1/32
# ==================== TUN 虚拟网卡 ====================
tun:
  enable: true
  device: mihomo
  stack: mixed
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  dns-hijack:
    - any:53
  route-exclude-address: []
  mtu: 1500
  strict-route: true
  disable-icmp-forwarding: false
# ==================== DNS ====================
dns:
  enable: true
  ipv6: false
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
    - +.lan
    - +.local
    - time.*.com
    - ntp.*.com
    - +.market.xiaomi.com
  use-hosts: false
  use-system-hosts: false
  default-nameserver:
    - tls://223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy: {}
  proxy-server-nameserver: []
  proxy-server-nameserver-policy: {}
  direct-nameserver: []
  fake-ip-range6: ""
# ==================== 域名嗅探 ====================
sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: false
  sniff:
    HTTP:
      ports:
        - 80
        - 443
      override-destination: false
    TLS:
      ports:
        - 443
  skip-domain:
    - +.push.apple.com
  skip-dst-address:
    - 91.105.192.0/23
    - 91.108.4.0/22
    - 91.108.8.0/21
    - 91.108.16.0/21
    - 91.108.56.0/22
    - 95.161.64.0/20
    - 149.154.160.0/20
    - 185.76.151.0/24
    - 2001:67c:4e8::/48
    - 2001:b28:f23c::/47
    - 2001:b28:f23f::/48
    - 2a0a:f280:203::/48
# ==================== 配置与 Geo 数据 ====================
profile:
  store-selected: true
  store-fake-ip: true
geo-auto-update: true
geo-update-interval: 24
geodata-mode: false
# ==================== Geo 数据下载地址 ====================
# 默认采用高效 MMDB / MetaDB 模式（geodata-mode: false），在此模式下 geoip.metadb 须填写在 geox-url.mmdb 字段中。
geox-url:
  geoip: https://github.com/appshubcc/bett-rules/releases/download/latest/geoip.dat
  geosite: https://github.com/appshubcc/bett-rules/releases/download/latest/geosite.dat
  mmdb: https://github.com/appshubcc/bett-rules/releases/download/latest/geoip.metadb
  asn: https://github.com/appshubcc/bett-rules/releases/download/latest/GeoLite2-ASN.mmdb

# ==================== 远程规则集 ====================
rule-providers:
  prevent_dns_leak:
    url: "https://raw.githubusercontent.com/xishang0128/rules/main/clash%20or%20stash/prevent_dns_leak/prevent_dns_leak_domain.list"
    path: ./ruleset/prevent_dns_leak_domain.list
    behavior: domain
    interval: 86400
    format: text
    type: http
  private:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.yaml
    path: ./ruleset/private.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
  cn_domain:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.yaml
    path: ./ruleset/cn_domain.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
  telegram_domain:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.yaml
    path: ./ruleset/telegram_domain.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
  google_domain:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.yaml
    path: ./ruleset/google_domain.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
  geolocation-!cn:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.yaml
    path: ./ruleset/geolocation-!cn.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
  cn_ip:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.yaml
    path: ./ruleset/cn_ip.yaml
    behavior: ipcidr
    interval: 86400
    format: yaml
    type: http
  telegram_ip:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/telegram.yaml
    path: ./ruleset/telegram_ip.yaml
    behavior: ipcidr
    interval: 86400
    format: yaml
    type: http
  google_ip:
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/google.yaml
    path: ./ruleset/google_ip.yaml
    behavior: ipcidr
    interval: 86400
    format: yaml
    type: http
  bing:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bing/Bing.yaml
    path: ./ruleset/bing.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
  copilot:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot.yaml
    path: ./ruleset/copilot.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
  claude:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.yaml
    path: ./ruleset/claude.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
  bard:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BardAI/BardAI.yaml
    path: ./ruleset/bard.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
  openai:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/openai.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
  steam:
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml
    path: ./ruleset/steam.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http

proxy-groups:
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Static.png
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    name: PROXY
    type: select
    proxies:
      - AUTO
      - HK AUTO
      - SG AUTO
      - JP AUTO
      - US AUTO
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Urltest.png
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    name: AUTO
    type: url-test
    interval: 60
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/OpenAI.png
    name: AIGC
    type: select
    proxies:
      - SG AUTO
      - JP AUTO
      - US AUTO
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Telegram.png
    name: Telegram
    type: select
    proxies:
      - HK AUTO
      - SG AUTO
      - JP AUTO
      - US AUTO
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Google.png
    name: Google
    type: select
    proxies:
      - HK AUTO
      - SG AUTO
      - JP AUTO
      - US AUTO
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/HK.png
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    filter: (?i)香港|Hong Kong|HK|🇭🇰
    name: HK AUTO
    type: url-test
    interval: 60
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/SG.png
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    filter: (?i)新加坡|Singapore|🇸🇬
    name: SG AUTO
    type: url-test
    interval: 60
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/JP.png
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    filter: (?i)日本|Japan|🇯🇵
    name: JP AUTO
    type: url-test
    interval: 60
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/US.png
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    filter: (?i)美国|USA|🇺🇸
    name: US AUTO
    type: url-test
    interval: 60
  - icon: https://testingcf.jsdelivr.net/gh/Orz-3/mini@master/Color/Global.png
    include-all: true
    exclude-filter: (?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置
    proxies:
      - PROXY
      - AUTO
      - AIGC
      - Telegram
      - Google
      - HK AUTO
      - SG AUTO
      - JP AUTO
      - US AUTO
    name: GLOBAL
    type: select

rules:
  - "RULE-SET,prevent_dns_leak,PROXY"
  - "RULE-SET,private,DIRECT"
  - "RULE-SET,bing,AIGC"
  - "RULE-SET,copilot,AIGC"
  - "RULE-SET,bard,AIGC"
  - "RULE-SET,openai,AIGC"
  - "RULE-SET,claude,AIGC"
  - "RULE-SET,steam,PROXY"
  - "RULE-SET,telegram_domain,Telegram"
  - "RULE-SET,telegram_ip,Telegram"
  - "RULE-SET,google_domain,Google"
  - "RULE-SET,google_ip,Google"
  - "RULE-SET,geolocation-!cn,PROXY"
  - "RULE-SET,cn_domain,DIRECT"
  - "RULE-SET,cn_ip,DIRECT"
  - "MATCH,PROXY"